### ISSUE TITLE
While running npm start throws error message

### ISSUE THREAD

**Issue by kalai6095** [kalai6095/tubeplaylistdownloader#1]
gitpod /workspace/tubeplaylistdownloader $ npm start

		> tubeplaylistdownloader@1.0.0 start /workspace/tubeplaylistdownloader
		> node server.js

		internal/modules/cjs/loader.js:638
			throw err;
			^

		Error: Cannot find module 'm3u8stream/lib/parse-time'
			at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
			at Function.Module._load (internal/modules/cjs/loader.js:562:25)
			at Module.require (internal/modules/cjs/loader.js:692:17)
			at require (internal/modules/cjs/helpers.js:25:18)
			at Object.<anonymous> (/workspace/tubeplaylistdownloader/node_modules/ytdl-core/lib/info-extras.js:5:21)
			at Module._compile (internal/modules/cjs/loader.js:778:30)
			at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
			at Module.load (internal/modules/cjs/loader.js:653:32)
			at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
			at Function.Module._load (internal/modules/cjs/loader.js:585:3)
		npm ERR! code ELIFECYCLE
		npm ERR! errno 1
		npm ERR! tubeplaylistdownloader@1.0.0 start: `node server.js`
		npm ERR! Exit status 1
		npm ERR! 
		npm ERR! Failed at the tubeplaylistdownloader@1.0.0 start script.
		npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

		npm ERR! A complete log of this run can be found in:
		npm ERR!     /home/gitpod/.npm/_logs/2019-11-26T13_30_10_160Z-debug.log

**Comment by kalai6095** [comment]
after npm i cmd need to run the below cmd
      
     cp -r ./node_modules/m3u8stream/dist ./node_modules/m3u8stream/lib
